Movie_Recommender/Movie_Recommender/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = 'core'))
]

Movie_Recommender/core/urls.py
from django.urls import path

from  .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView),
   

    path('search/',SearchView.as_view(), name="search"),
    path('genre',GenreView, name="genre"),
    path('imdb',imdbView, name="imdb"),
    path('plot',plotView, name="plot"),



    
]

Movie_Recommender/core/models.py
from django.db import models

class Movie(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

Movie_Recommender/core/views.py
from django.template import RequestContext, loader
from PIL import Image
import requests
import io
from io import BytesIO
from numbers import Complex
from django import template
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.context import RequestContext
from django.views import View
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from numpy.core.numeric import moveaxis
from django.template import Context

from .models import Movie
from django.shortcuts import render

import sys
from django.views.generic import ListView
from recom import get_movie



 
""" class HomeView(ListView):
    model = Movie 
    template_name = 'base.html """

def HomeView(request):
    return render(request,'base.html')

class SearchView(TemplateView):
    template_name = "search.html"   

    def get_context_data(self, **kwargs):

        context =  super().get_context_data(**kwargs)
        genre_name =  self.request.GET.get("genre")
               
        movie_list, movie_img = get_movie(genre_name)
        context["movie_list"] = movie_list
        # base_url = "https://image.tmdb.org/t/p/original"
        #img_list = []
        #for item in movie_img:
           # img = base_url + str(item)
           # img_list.append(img) 
        
        #img_list2 = []
        #for image in img_list:
            
            #response = requests.get(image, stream=True)
            #file_like_object = response.raw

            #file_like_object = io.BytesIO()
            #file_like_object.write(response.content)
            #file_like_object.seek(0)
            #image_li = Image.open(BytesIO(response.content))
            #image_li.show()
            #return (file_like_object, mimetype = 'image/type')

        #context["img_list2"] = img_list2
        
  # def get_image_bytesio(img_list):
       # for i in img_list:
        #    r = requests.get(i)

          #  file_like_object = io.BytesIO()
          #  file_like_object.write(r.content)
          #  file_like_object.seek(0)  # move to the beginning of file after writing

        #return HttpResponse(file_like_object, content_type
       # ='image/png')    
        return context
        

def GenreView(request):
    return render(request, 'genre.html')

def imdbView(request):
    return render(request, 'imdb.html')

def plotView(request):
    return render(request, 'plot.html')

Movie_Recommender/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>Movie Recommender</title>
    <link type="text/css" rel="stylesheet" href="{%static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"
    />
  </head>
  <body>
    <h4>FIND MOVIES BASED ON</h4>

    <div class="container">
      <a href="{% url 'core:genre' %}">
        <div class="card card0">
          <div class="border">
            <h2>Genre</h2>
            <div class="icons">
              <i class="fa fa-film" aria-hidden="true"></i>
            </div>
          </div>
        </div>
      </a>



    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.12.1/plugins/CSSRulePlugin.min.js"></script>
  </body>
</html>

Movie_Recommender/templates/genre.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <script></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"
    />

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Genre</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link type="text/css" rel="stylesheet" href="{%static 'css/genre.css' %}" />
  </head>
  <body>
    <form class="form__group field" method="GET" action="search/">
      <div>
        <input
          type="input"
          class="form__field"
          placeholder="Genre"
          name="genre"
          id="genre"
          required
        />
        <label for="genre" class="form__label">Enter Genre, Keyword</label>
      </div>

      <button class="btn" type="submit">
        <span class="btnspan">&rarr; </span>
      </button>
    </form>
    <script src="static/css/main.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </body>
</html>

Movie_Recommender/templates/imdb.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    yolooo

    <script src="" async defer></script>
  </body>
</html>

Movie_Recommender/templates/search.html
{% load static%}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      type="text/css"
      rel="stylesheet"
      href="{%static 'css/search.css' %}"
    />
  </head>
  <body>
    <h3>Search results for <span>{{ request.GET.genre }}</span></h3>
    <span class="mve"
      >{% for movie in movie_list %} {{ movie |linebreaks }} {% endfor %}
    </span>
   <span class="img" {% for img in img_list2 %} {{ img |linebreaks }} {% endfor %}</span>
  </body>
</html>